server:
  port: 8081

spring:
  application:
    name: banking-operations-service
  datasource:
    url: jdbc:postgresql://localhost:5432/finsight
    username: finsight
    password: finsight
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

finsight:
  kafka:
    topic: banking.operations.events
